name: Deploy React App to G3 Server

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Rebuild Docker container
        run: |
          rm -rf ~/projects/translation-cleaner/*
          mkdir -p ~/projects/translation-cleaner
          cp -r . ~/projects/translation-cleaner
          cd ~/projects/translation-cleaner
          docker compose down
          docker compose up -d --build
