version: '3.9'
services:
  translation-app:
    image: translation-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation-app
    ports:
      - "3000:80"
    restart: unless-stopped
